export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GITHUB_USER_LOADING = 'FETCH/LOADING/GITHUB/USER'
export const GITHUB_USER_SUCCESS = 'FETCH/SUCCESS/GITHUB/USER'
export const GITHUB_USER_ERROR = 'FETCH/ERROR/GITHUB/USER'

export const GITHUB_USER_CLEAR = 'CLEAR/GITHUB/USER'
